services:
  rundeck:
    container_name: rundeck_oss
    image: rundeck/rundeck:5.6.0
    ports:
      - "4440:4440"
    environment:
      RUNDECK_GRAILS_URL: http://localhost:4440
    networks:
      - rundeck
  gitea:
    image: gitea/gitea:1.22.2
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - "3000:3000"
      - "2220:22"
    volumes:
      - ./gitea_data:/var/lib/gitea
      - ./gitea_config:/etc/gitea
    networks:
      - rundeck
networks:
  rundeck:
